// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParseServiceClient is the client API for ParseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParseServiceClient interface {
	Parse(ctx context.Context, in *PathsToFiles, opts ...grpc.CallOption) (*Result, error)
}

type parseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParseServiceClient(cc grpc.ClientConnInterface) ParseServiceClient {
	return &parseServiceClient{cc}
}

func (c *parseServiceClient) Parse(ctx context.Context, in *PathsToFiles, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/grpc.ParseService/Parse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParseServiceServer is the server API for ParseService service.
// All implementations must embed UnimplementedParseServiceServer
// for forward compatibility
type ParseServiceServer interface {
	Parse(context.Context, *PathsToFiles) (*Result, error)
	mustEmbedUnimplementedParseServiceServer()
}

// UnimplementedParseServiceServer must be embedded to have forward compatible implementations.
type UnimplementedParseServiceServer struct {
}

func (UnimplementedParseServiceServer) Parse(context.Context, *PathsToFiles) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedParseServiceServer) mustEmbedUnimplementedParseServiceServer() {}

// UnsafeParseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParseServiceServer will
// result in compilation errors.
type UnsafeParseServiceServer interface {
	mustEmbedUnimplementedParseServiceServer()
}

func RegisterParseServiceServer(s grpc.ServiceRegistrar, srv ParseServiceServer) {
	s.RegisterService(&ParseService_ServiceDesc, srv)
}

func _ParseService_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathsToFiles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParseServiceServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ParseService/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParseServiceServer).Parse(ctx, req.(*PathsToFiles))
	}
	return interceptor(ctx, in, info, handler)
}

// ParseService_ServiceDesc is the grpc.ServiceDesc for ParseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ParseService",
	HandlerType: (*ParseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _ParseService_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/parse.proto",
}
