// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gedcom/gedcom.proto

package gedcom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gedcom struct {
	Individuals          []*Gedcom_Individual `protobuf:"bytes,1,rep,name=Individuals,proto3" json:"Individuals,omitempty"`
	Families             []*Gedcom_Family     `protobuf:"bytes,2,rep,name=Families,proto3" json:"Families,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Gedcom) Reset()         { *m = Gedcom{} }
func (m *Gedcom) String() string { return proto.CompactTextString(m) }
func (*Gedcom) ProtoMessage()    {}
func (*Gedcom) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba894296bd701711, []int{0}
}

func (m *Gedcom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom.Unmarshal(m, b)
}
func (m *Gedcom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom.Marshal(b, m, deterministic)
}
func (m *Gedcom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom.Merge(m, src)
}
func (m *Gedcom) XXX_Size() int {
	return xxx_messageInfo_Gedcom.Size(m)
}
func (m *Gedcom) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom proto.InternalMessageInfo

func (m *Gedcom) GetIndividuals() []*Gedcom_Individual {
	if m != nil {
		return m.Individuals
	}
	return nil
}

func (m *Gedcom) GetFamilies() []*Gedcom_Family {
	if m != nil {
		return m.Families
	}
	return nil
}

type Gedcom_Individual struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Names                []*Gedcom_Individual_Name  `protobuf:"bytes,2,rep,name=Names,proto3" json:"Names,omitempty"`
	Gender               string                     `protobuf:"bytes,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	BirthEvents          []*Gedcom_Individual_Event `protobuf:"bytes,4,rep,name=BirthEvents,proto3" json:"BirthEvents,omitempty"`
	DeathEvents          []*Gedcom_Individual_Event `protobuf:"bytes,5,rep,name=DeathEvents,proto3" json:"DeathEvents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Gedcom_Individual) Reset()         { *m = Gedcom_Individual{} }
func (m *Gedcom_Individual) String() string { return proto.CompactTextString(m) }
func (*Gedcom_Individual) ProtoMessage()    {}
func (*Gedcom_Individual) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba894296bd701711, []int{0, 0}
}

func (m *Gedcom_Individual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom_Individual.Unmarshal(m, b)
}
func (m *Gedcom_Individual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom_Individual.Marshal(b, m, deterministic)
}
func (m *Gedcom_Individual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom_Individual.Merge(m, src)
}
func (m *Gedcom_Individual) XXX_Size() int {
	return xxx_messageInfo_Gedcom_Individual.Size(m)
}
func (m *Gedcom_Individual) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom_Individual.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom_Individual proto.InternalMessageInfo

func (m *Gedcom_Individual) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gedcom_Individual) GetNames() []*Gedcom_Individual_Name {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Gedcom_Individual) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Gedcom_Individual) GetBirthEvents() []*Gedcom_Individual_Event {
	if m != nil {
		return m.BirthEvents
	}
	return nil
}

func (m *Gedcom_Individual) GetDeathEvents() []*Gedcom_Individual_Event {
	if m != nil {
		return m.DeathEvents
	}
	return nil
}

type Gedcom_Individual_Event struct {
	Date                 *Gedcom_Individual_Date `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Place                string                  `protobuf:"bytes,2,opt,name=Place,proto3" json:"Place,omitempty"`
	Primary              bool                    `protobuf:"varint,3,opt,name=Primary,proto3" json:"Primary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Gedcom_Individual_Event) Reset()         { *m = Gedcom_Individual_Event{} }
func (m *Gedcom_Individual_Event) String() string { return proto.CompactTextString(m) }
func (*Gedcom_Individual_Event) ProtoMessage()    {}
func (*Gedcom_Individual_Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba894296bd701711, []int{0, 0, 0}
}

func (m *Gedcom_Individual_Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom_Individual_Event.Unmarshal(m, b)
}
func (m *Gedcom_Individual_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom_Individual_Event.Marshal(b, m, deterministic)
}
func (m *Gedcom_Individual_Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom_Individual_Event.Merge(m, src)
}
func (m *Gedcom_Individual_Event) XXX_Size() int {
	return xxx_messageInfo_Gedcom_Individual_Event.Size(m)
}
func (m *Gedcom_Individual_Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom_Individual_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom_Individual_Event proto.InternalMessageInfo

func (m *Gedcom_Individual_Event) GetDate() *Gedcom_Individual_Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Gedcom_Individual_Event) GetPlace() string {
	if m != nil {
		return m.Place
	}
	return ""
}

func (m *Gedcom_Individual_Event) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

type Gedcom_Individual_Name struct {
	GivenName            string   `protobuf:"bytes,1,opt,name=GivenName,proto3" json:"GivenName,omitempty"`
	Surname              string   `protobuf:"bytes,2,opt,name=Surname,proto3" json:"Surname,omitempty"`
	Primary              bool     `protobuf:"varint,3,opt,name=Primary,proto3" json:"Primary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gedcom_Individual_Name) Reset()         { *m = Gedcom_Individual_Name{} }
func (m *Gedcom_Individual_Name) String() string { return proto.CompactTextString(m) }
func (*Gedcom_Individual_Name) ProtoMessage()    {}
func (*Gedcom_Individual_Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba894296bd701711, []int{0, 0, 1}
}

func (m *Gedcom_Individual_Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom_Individual_Name.Unmarshal(m, b)
}
func (m *Gedcom_Individual_Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom_Individual_Name.Marshal(b, m, deterministic)
}
func (m *Gedcom_Individual_Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom_Individual_Name.Merge(m, src)
}
func (m *Gedcom_Individual_Name) XXX_Size() int {
	return xxx_messageInfo_Gedcom_Individual_Name.Size(m)
}
func (m *Gedcom_Individual_Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom_Individual_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom_Individual_Name proto.InternalMessageInfo

func (m *Gedcom_Individual_Name) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *Gedcom_Individual_Name) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Gedcom_Individual_Name) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

type Gedcom_Individual_Date struct {
	Year                 uint32   `protobuf:"varint,1,opt,name=Year,proto3" json:"Year,omitempty"`
	Month                uint32   `protobuf:"varint,2,opt,name=Month,proto3" json:"Month,omitempty"`
	Day                  uint32   `protobuf:"varint,3,opt,name=Day,proto3" json:"Day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gedcom_Individual_Date) Reset()         { *m = Gedcom_Individual_Date{} }
func (m *Gedcom_Individual_Date) String() string { return proto.CompactTextString(m) }
func (*Gedcom_Individual_Date) ProtoMessage()    {}
func (*Gedcom_Individual_Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba894296bd701711, []int{0, 0, 2}
}

func (m *Gedcom_Individual_Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom_Individual_Date.Unmarshal(m, b)
}
func (m *Gedcom_Individual_Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom_Individual_Date.Marshal(b, m, deterministic)
}
func (m *Gedcom_Individual_Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom_Individual_Date.Merge(m, src)
}
func (m *Gedcom_Individual_Date) XXX_Size() int {
	return xxx_messageInfo_Gedcom_Individual_Date.Size(m)
}
func (m *Gedcom_Individual_Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom_Individual_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom_Individual_Date proto.InternalMessageInfo

func (m *Gedcom_Individual_Date) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Gedcom_Individual_Date) GetMonth() uint32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Gedcom_Individual_Date) GetDay() uint32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type Gedcom_Family struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FatherId             string   `protobuf:"bytes,2,opt,name=FatherId,proto3" json:"FatherId,omitempty"`
	MotherId             string   `protobuf:"bytes,3,opt,name=MotherId,proto3" json:"MotherId,omitempty"`
	ChildIds             []string `protobuf:"bytes,4,rep,name=ChildIds,proto3" json:"ChildIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gedcom_Family) Reset()         { *m = Gedcom_Family{} }
func (m *Gedcom_Family) String() string { return proto.CompactTextString(m) }
func (*Gedcom_Family) ProtoMessage()    {}
func (*Gedcom_Family) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba894296bd701711, []int{0, 1}
}

func (m *Gedcom_Family) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom_Family.Unmarshal(m, b)
}
func (m *Gedcom_Family) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom_Family.Marshal(b, m, deterministic)
}
func (m *Gedcom_Family) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom_Family.Merge(m, src)
}
func (m *Gedcom_Family) XXX_Size() int {
	return xxx_messageInfo_Gedcom_Family.Size(m)
}
func (m *Gedcom_Family) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom_Family.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom_Family proto.InternalMessageInfo

func (m *Gedcom_Family) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gedcom_Family) GetFatherId() string {
	if m != nil {
		return m.FatherId
	}
	return ""
}

func (m *Gedcom_Family) GetMotherId() string {
	if m != nil {
		return m.MotherId
	}
	return ""
}

func (m *Gedcom_Family) GetChildIds() []string {
	if m != nil {
		return m.ChildIds
	}
	return nil
}

func init() {
	proto.RegisterType((*Gedcom)(nil), "gedcom.Gedcom")
	proto.RegisterType((*Gedcom_Individual)(nil), "gedcom.Gedcom.Individual")
	proto.RegisterType((*Gedcom_Individual_Event)(nil), "gedcom.Gedcom.Individual.Event")
	proto.RegisterType((*Gedcom_Individual_Name)(nil), "gedcom.Gedcom.Individual.Name")
	proto.RegisterType((*Gedcom_Individual_Date)(nil), "gedcom.Gedcom.Individual.Date")
	proto.RegisterType((*Gedcom_Family)(nil), "gedcom.Gedcom.Family")
}

func init() { proto.RegisterFile("gedcom/gedcom.proto", fileDescriptor_ba894296bd701711) }

var fileDescriptor_ba894296bd701711 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4f, 0x3a, 0x31,
	0x10, 0xc6, 0xc3, 0xbe, 0xfd, 0x61, 0x08, 0xff, 0x98, 0xfa, 0x92, 0xba, 0x31, 0x4a, 0x3c, 0x71,
	0x5a, 0x23, 0x7a, 0xf3, 0x24, 0xa2, 0x64, 0x0f, 0x18, 0x52, 0x2f, 0x7a, 0xac, 0xb4, 0x71, 0x1b,
	0xf7, 0xc5, 0x94, 0x85, 0x84, 0xef, 0xeb, 0xb7, 0xf0, 0x62, 0x3a, 0x5d, 0x16, 0xa2, 0x81, 0x78,
	0xda, 0x79, 0x76, 0x9e, 0xe7, 0x97, 0x99, 0xb6, 0xb0, 0xff, 0x26, 0xc5, 0xb4, 0xc8, 0x2e, 0xec,
	0x27, 0xfa, 0xd0, 0x45, 0x59, 0x90, 0xc0, 0xaa, 0xf3, 0x4f, 0x1f, 0x82, 0x11, 0x96, 0xe4, 0x06,
	0xda, 0x71, 0x2e, 0xd4, 0x42, 0x89, 0x39, 0x4f, 0x67, 0xb4, 0xd1, 0x75, 0x7b, 0xed, 0xfe, 0x71,
	0x54, 0xc5, 0xac, 0x29, 0x5a, 0x3b, 0xd8, 0xa6, 0x9b, 0x5c, 0x42, 0xf3, 0x81, 0x67, 0x2a, 0x55,
	0x72, 0x46, 0x1d, 0x4c, 0x1e, 0xfe, 0x48, 0x62, 0x7b, 0xc9, 0x6a, 0x5b, 0xf8, 0xe5, 0x02, 0xac,
	0x11, 0xe4, 0x3f, 0x38, 0xb1, 0xa0, 0x8d, 0x6e, 0xa3, 0xd7, 0x62, 0x4e, 0x2c, 0xc8, 0x35, 0xf8,
	0x8f, 0x3c, 0xab, 0x71, 0xa7, 0x5b, 0x07, 0x89, 0x8c, 0x8d, 0x59, 0x33, 0x39, 0x32, 0xeb, 0xe4,
	0x42, 0x6a, 0xea, 0x22, 0xa9, 0x52, 0xe4, 0x16, 0xda, 0x03, 0xa5, 0xcb, 0xe4, 0x7e, 0x21, 0xf3,
	0x72, 0x46, 0x3d, 0x64, 0x9e, 0x6d, 0x67, 0xa2, 0x8f, 0x6d, 0x66, 0x0c, 0x62, 0x28, 0x79, 0x8d,
	0xf0, 0xff, 0x88, 0xd8, 0xc8, 0x84, 0xef, 0xe0, 0x63, 0x45, 0xfa, 0xe0, 0x0d, 0x79, 0x29, 0x71,
	0xdd, 0x9d, 0xbb, 0x19, 0x17, 0x43, 0x2f, 0x39, 0x00, 0x7f, 0x92, 0xf2, 0xa9, 0xa4, 0x0e, 0x6e,
	0x66, 0x05, 0xa1, 0xf0, 0x6f, 0xa2, 0x55, 0xc6, 0xf5, 0x12, 0x37, 0x6e, 0xb2, 0x95, 0x0c, 0x9f,
	0xc1, 0x33, 0x67, 0x42, 0x4e, 0xa0, 0x35, 0x52, 0x0b, 0x99, 0x1b, 0x51, 0x9d, 0xef, 0xfa, 0x87,
	0xc9, 0x3f, 0xcd, 0x75, 0x6e, 0x7a, 0x96, 0xbb, 0x92, 0x3b, 0xc8, 0x03, 0x3b, 0x3d, 0x21, 0xe0,
	0xbd, 0x48, 0xae, 0x11, 0xda, 0x61, 0x58, 0x9b, 0x29, 0xc7, 0x45, 0x5e, 0x26, 0x48, 0xeb, 0x30,
	0x2b, 0xc8, 0x1e, 0xb8, 0x43, 0x6e, 0x39, 0x1d, 0x66, 0xca, 0x30, 0x85, 0xc0, 0xbe, 0x88, 0x5f,
	0x17, 0x1f, 0x9a, 0xa7, 0x54, 0x26, 0x52, 0xc7, 0xa2, 0x1a, 0xa9, 0xd6, 0xa6, 0x37, 0x2e, 0xaa,
	0x9e, 0xbd, 0xe0, 0x5a, 0x9b, 0xde, 0x5d, 0xa2, 0x52, 0x11, 0x0b, 0x7b, 0xbf, 0x2d, 0x56, 0xeb,
	0xd7, 0x00, 0x5f, 0xfd, 0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0xe0, 0xb9, 0x98, 0x0c,
	0x03, 0x00, 0x00,
}
