// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gedcom.proto

package gedcom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gedcom struct {
	Individuals          []*Gedcom_Individual `protobuf:"bytes,1,rep,name=Individuals,proto3" json:"Individuals,omitempty"`
	Families             []*Gedcom_Family     `protobuf:"bytes,2,rep,name=Families,proto3" json:"Families,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Gedcom) Reset()         { *m = Gedcom{} }
func (m *Gedcom) String() string { return proto.CompactTextString(m) }
func (*Gedcom) ProtoMessage()    {}
func (*Gedcom) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8369417c5c80200, []int{0}
}

func (m *Gedcom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom.Unmarshal(m, b)
}
func (m *Gedcom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom.Marshal(b, m, deterministic)
}
func (m *Gedcom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom.Merge(m, src)
}
func (m *Gedcom) XXX_Size() int {
	return xxx_messageInfo_Gedcom.Size(m)
}
func (m *Gedcom) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom proto.InternalMessageInfo

func (m *Gedcom) GetIndividuals() []*Gedcom_Individual {
	if m != nil {
		return m.Individuals
	}
	return nil
}

func (m *Gedcom) GetFamilies() []*Gedcom_Family {
	if m != nil {
		return m.Families
	}
	return nil
}

type Gedcom_Individual struct {
	Id                   string                    `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Names                []*Gedcom_Individual_Name `protobuf:"bytes,2,rep,name=Names,proto3" json:"Names,omitempty"`
	Gender               string                    `protobuf:"bytes,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Gedcom_Individual) Reset()         { *m = Gedcom_Individual{} }
func (m *Gedcom_Individual) String() string { return proto.CompactTextString(m) }
func (*Gedcom_Individual) ProtoMessage()    {}
func (*Gedcom_Individual) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8369417c5c80200, []int{0, 0}
}

func (m *Gedcom_Individual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom_Individual.Unmarshal(m, b)
}
func (m *Gedcom_Individual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom_Individual.Marshal(b, m, deterministic)
}
func (m *Gedcom_Individual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom_Individual.Merge(m, src)
}
func (m *Gedcom_Individual) XXX_Size() int {
	return xxx_messageInfo_Gedcom_Individual.Size(m)
}
func (m *Gedcom_Individual) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom_Individual.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom_Individual proto.InternalMessageInfo

func (m *Gedcom_Individual) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gedcom_Individual) GetNames() []*Gedcom_Individual_Name {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Gedcom_Individual) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type Gedcom_Individual_Name struct {
	GivenName            string   `protobuf:"bytes,1,opt,name=GivenName,proto3" json:"GivenName,omitempty"`
	Surname              string   `protobuf:"bytes,2,opt,name=Surname,proto3" json:"Surname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gedcom_Individual_Name) Reset()         { *m = Gedcom_Individual_Name{} }
func (m *Gedcom_Individual_Name) String() string { return proto.CompactTextString(m) }
func (*Gedcom_Individual_Name) ProtoMessage()    {}
func (*Gedcom_Individual_Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8369417c5c80200, []int{0, 0, 0}
}

func (m *Gedcom_Individual_Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom_Individual_Name.Unmarshal(m, b)
}
func (m *Gedcom_Individual_Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom_Individual_Name.Marshal(b, m, deterministic)
}
func (m *Gedcom_Individual_Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom_Individual_Name.Merge(m, src)
}
func (m *Gedcom_Individual_Name) XXX_Size() int {
	return xxx_messageInfo_Gedcom_Individual_Name.Size(m)
}
func (m *Gedcom_Individual_Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom_Individual_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom_Individual_Name proto.InternalMessageInfo

func (m *Gedcom_Individual_Name) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *Gedcom_Individual_Name) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

type Gedcom_Family struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FatherId             string   `protobuf:"bytes,2,opt,name=FatherId,proto3" json:"FatherId,omitempty"`
	MotherId             string   `protobuf:"bytes,3,opt,name=MotherId,proto3" json:"MotherId,omitempty"`
	ChildIds             []string `protobuf:"bytes,4,rep,name=ChildIds,proto3" json:"ChildIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gedcom_Family) Reset()         { *m = Gedcom_Family{} }
func (m *Gedcom_Family) String() string { return proto.CompactTextString(m) }
func (*Gedcom_Family) ProtoMessage()    {}
func (*Gedcom_Family) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8369417c5c80200, []int{0, 1}
}

func (m *Gedcom_Family) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gedcom_Family.Unmarshal(m, b)
}
func (m *Gedcom_Family) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gedcom_Family.Marshal(b, m, deterministic)
}
func (m *Gedcom_Family) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gedcom_Family.Merge(m, src)
}
func (m *Gedcom_Family) XXX_Size() int {
	return xxx_messageInfo_Gedcom_Family.Size(m)
}
func (m *Gedcom_Family) XXX_DiscardUnknown() {
	xxx_messageInfo_Gedcom_Family.DiscardUnknown(m)
}

var xxx_messageInfo_Gedcom_Family proto.InternalMessageInfo

func (m *Gedcom_Family) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gedcom_Family) GetFatherId() string {
	if m != nil {
		return m.FatherId
	}
	return ""
}

func (m *Gedcom_Family) GetMotherId() string {
	if m != nil {
		return m.MotherId
	}
	return ""
}

func (m *Gedcom_Family) GetChildIds() []string {
	if m != nil {
		return m.ChildIds
	}
	return nil
}

func init() {
	proto.RegisterType((*Gedcom)(nil), "model.Gedcom")
	proto.RegisterType((*Gedcom_Individual)(nil), "model.Gedcom.Individual")
	proto.RegisterType((*Gedcom_Individual_Name)(nil), "model.Gedcom.Individual.Name")
	proto.RegisterType((*Gedcom_Family)(nil), "model.Gedcom.Family")
}

func init() { proto.RegisterFile("gedcom.proto", fileDescriptor_b8369417c5c80200) }

var fileDescriptor_b8369417c5c80200 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xd2, 0x46, 0x3b, 0x15, 0x0f, 0x83, 0xc8, 0x12, 0x14, 0x82, 0xa7, 0x9e, 0x16,
	0xb1, 0x37, 0x0f, 0x5e, 0x04, 0xcb, 0x1e, 0xf4, 0x10, 0x9f, 0x20, 0x3a, 0x8b, 0x5d, 0xd8, 0x64,
	0x25, 0x69, 0x0b, 0xbe, 0x85, 0xaf, 0xe1, 0x5b, 0xca, 0x6c, 0x36, 0x1b, 0x45, 0x3c, 0xfe, 0xfb,
	0x7d, 0x33, 0xf9, 0x87, 0xc0, 0xc9, 0x9b, 0xa6, 0x57, 0xd7, 0xc8, 0xf7, 0xce, 0xed, 0x1c, 0xce,
	0x1b, 0x47, 0xda, 0x5e, 0x7d, 0x66, 0x90, 0x6f, 0xfc, 0x3b, 0xde, 0xc2, 0x52, 0xb5, 0x64, 0x0e,
	0x86, 0xf6, 0xb5, 0xed, 0x45, 0x52, 0x66, 0xab, 0xe5, 0x8d, 0x90, 0xde, 0x93, 0x83, 0x23, 0x27,
	0xa1, 0xfa, 0x29, 0xe3, 0x35, 0x1c, 0x3f, 0xd4, 0x8d, 0xb1, 0x46, 0xf7, 0x22, 0xf5, 0x83, 0x67,
	0xbf, 0x07, 0x3d, 0xfd, 0xa8, 0xa2, 0x55, 0x7c, 0x25, 0x00, 0xd3, 0x06, 0x3c, 0x85, 0x54, 0x91,
	0x48, 0xca, 0x64, 0xb5, 0xa8, 0x52, 0x45, 0xb8, 0x86, 0xf9, 0x53, 0xdd, 0xc4, 0x6d, 0x97, 0xff,
	0xd5, 0x90, 0x6c, 0x55, 0x83, 0x8b, 0xe7, 0x7c, 0x4b, 0x4b, 0xba, 0x13, 0x99, 0x5f, 0x14, 0x52,
	0x71, 0x07, 0x33, 0x16, 0xf0, 0x02, 0x16, 0x1b, 0x73, 0xd0, 0x2d, 0x87, 0xf0, 0xad, 0xe9, 0x01,
	0x05, 0x1c, 0x3d, 0xef, 0xbb, 0x96, 0x59, 0xea, 0xd9, 0x18, 0x0b, 0x0b, 0xf9, 0xd0, 0xff, 0x4f,
	0xcd, 0x82, 0xef, 0xde, 0x6d, 0x75, 0xa7, 0x28, 0x0c, 0xc5, 0xcc, 0xec, 0xd1, 0x05, 0x36, 0xf4,
	0x89, 0x99, 0xd9, 0xfd, 0xd6, 0x58, 0x52, 0xd4, 0x8b, 0x59, 0x99, 0x31, 0x1b, 0xf3, 0x4b, 0xee,
	0x7f, 0xd0, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xf4, 0x3f, 0xa9, 0xb0, 0x01, 0x00, 0x00,
}
