// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.11.3
// source: gedcom/gedcom.proto

package gedcom

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Gedcom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header      *Gedcom_HeaderType   `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Individuals []*Gedcom_Individual `protobuf:"bytes,2,rep,name=Individuals,proto3" json:"Individuals,omitempty"`
	Families    []*Gedcom_Family     `protobuf:"bytes,3,rep,name=Families,proto3" json:"Families,omitempty"`
}

func (x *Gedcom) Reset() {
	*x = Gedcom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gedcom_gedcom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gedcom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gedcom) ProtoMessage() {}

func (x *Gedcom) ProtoReflect() protoreflect.Message {
	mi := &file_gedcom_gedcom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gedcom.ProtoReflect.Descriptor instead.
func (*Gedcom) Descriptor() ([]byte, []int) {
	return file_gedcom_gedcom_proto_rawDescGZIP(), []int{0}
}

func (x *Gedcom) GetHeader() *Gedcom_HeaderType {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Gedcom) GetIndividuals() []*Gedcom_Individual {
	if x != nil {
		return x.Individuals
	}
	return nil
}

func (x *Gedcom) GetFamilies() []*Gedcom_Family {
	if x != nil {
		return x.Families
	}
	return nil
}

type Gedcom_HeaderType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
}

func (x *Gedcom_HeaderType) Reset() {
	*x = Gedcom_HeaderType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gedcom_gedcom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gedcom_HeaderType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gedcom_HeaderType) ProtoMessage() {}

func (x *Gedcom_HeaderType) ProtoReflect() protoreflect.Message {
	mi := &file_gedcom_gedcom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gedcom_HeaderType.ProtoReflect.Descriptor instead.
func (*Gedcom_HeaderType) Descriptor() ([]byte, []int) {
	return file_gedcom_gedcom_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Gedcom_HeaderType) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Gedcom_Individual struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                     `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Names       []*Gedcom_Individual_Name  `protobuf:"bytes,2,rep,name=Names,proto3" json:"Names,omitempty"`
	Gender      string                     `protobuf:"bytes,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	BirthEvents []*Gedcom_Individual_Event `protobuf:"bytes,4,rep,name=BirthEvents,proto3" json:"BirthEvents,omitempty"`
	DeathEvents []*Gedcom_Individual_Event `protobuf:"bytes,5,rep,name=DeathEvents,proto3" json:"DeathEvents,omitempty"`
}

func (x *Gedcom_Individual) Reset() {
	*x = Gedcom_Individual{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gedcom_gedcom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gedcom_Individual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gedcom_Individual) ProtoMessage() {}

func (x *Gedcom_Individual) ProtoReflect() protoreflect.Message {
	mi := &file_gedcom_gedcom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gedcom_Individual.ProtoReflect.Descriptor instead.
func (*Gedcom_Individual) Descriptor() ([]byte, []int) {
	return file_gedcom_gedcom_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Gedcom_Individual) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gedcom_Individual) GetNames() []*Gedcom_Individual_Name {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Gedcom_Individual) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Gedcom_Individual) GetBirthEvents() []*Gedcom_Individual_Event {
	if x != nil {
		return x.BirthEvents
	}
	return nil
}

func (x *Gedcom_Individual) GetDeathEvents() []*Gedcom_Individual_Event {
	if x != nil {
		return x.DeathEvents
	}
	return nil
}

type Gedcom_Family struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FatherId string   `protobuf:"bytes,2,opt,name=FatherId,proto3" json:"FatherId,omitempty"`
	MotherId string   `protobuf:"bytes,3,opt,name=MotherId,proto3" json:"MotherId,omitempty"`
	ChildIds []string `protobuf:"bytes,4,rep,name=ChildIds,proto3" json:"ChildIds,omitempty"`
}

func (x *Gedcom_Family) Reset() {
	*x = Gedcom_Family{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gedcom_gedcom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gedcom_Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gedcom_Family) ProtoMessage() {}

func (x *Gedcom_Family) ProtoReflect() protoreflect.Message {
	mi := &file_gedcom_gedcom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gedcom_Family.ProtoReflect.Descriptor instead.
func (*Gedcom_Family) Descriptor() ([]byte, []int) {
	return file_gedcom_gedcom_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Gedcom_Family) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gedcom_Family) GetFatherId() string {
	if x != nil {
		return x.FatherId
	}
	return ""
}

func (x *Gedcom_Family) GetMotherId() string {
	if x != nil {
		return x.MotherId
	}
	return ""
}

func (x *Gedcom_Family) GetChildIds() []string {
	if x != nil {
		return x.ChildIds
	}
	return nil
}

type Gedcom_Individual_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date    *Gedcom_Individual_Date `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Place   string                  `protobuf:"bytes,2,opt,name=Place,proto3" json:"Place,omitempty"`
	Primary bool                    `protobuf:"varint,3,opt,name=Primary,proto3" json:"Primary,omitempty"`
}

func (x *Gedcom_Individual_Event) Reset() {
	*x = Gedcom_Individual_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gedcom_gedcom_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gedcom_Individual_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gedcom_Individual_Event) ProtoMessage() {}

func (x *Gedcom_Individual_Event) ProtoReflect() protoreflect.Message {
	mi := &file_gedcom_gedcom_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gedcom_Individual_Event.ProtoReflect.Descriptor instead.
func (*Gedcom_Individual_Event) Descriptor() ([]byte, []int) {
	return file_gedcom_gedcom_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Gedcom_Individual_Event) GetDate() *Gedcom_Individual_Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Gedcom_Individual_Event) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *Gedcom_Individual_Event) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

type Gedcom_Individual_Name struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GivenName string `protobuf:"bytes,1,opt,name=GivenName,proto3" json:"GivenName,omitempty"`
	Surname   string `protobuf:"bytes,2,opt,name=Surname,proto3" json:"Surname,omitempty"`
	Primary   bool   `protobuf:"varint,3,opt,name=Primary,proto3" json:"Primary,omitempty"`
}

func (x *Gedcom_Individual_Name) Reset() {
	*x = Gedcom_Individual_Name{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gedcom_gedcom_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gedcom_Individual_Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gedcom_Individual_Name) ProtoMessage() {}

func (x *Gedcom_Individual_Name) ProtoReflect() protoreflect.Message {
	mi := &file_gedcom_gedcom_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gedcom_Individual_Name.ProtoReflect.Descriptor instead.
func (*Gedcom_Individual_Name) Descriptor() ([]byte, []int) {
	return file_gedcom_gedcom_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Gedcom_Individual_Name) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *Gedcom_Individual_Name) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *Gedcom_Individual_Name) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

type Gedcom_Individual_Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year  string `protobuf:"bytes,1,opt,name=Year,proto3" json:"Year,omitempty"`
	Month string `protobuf:"bytes,2,opt,name=Month,proto3" json:"Month,omitempty"`
	Day   string `protobuf:"bytes,3,opt,name=Day,proto3" json:"Day,omitempty"`
}

func (x *Gedcom_Individual_Date) Reset() {
	*x = Gedcom_Individual_Date{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gedcom_gedcom_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gedcom_Individual_Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gedcom_Individual_Date) ProtoMessage() {}

func (x *Gedcom_Individual_Date) ProtoReflect() protoreflect.Message {
	mi := &file_gedcom_gedcom_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gedcom_Individual_Date.ProtoReflect.Descriptor instead.
func (*Gedcom_Individual_Date) Descriptor() ([]byte, []int) {
	return file_gedcom_gedcom_proto_rawDescGZIP(), []int{0, 1, 2}
}

func (x *Gedcom_Individual_Date) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Gedcom_Individual_Date) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *Gedcom_Individual_Date) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

var File_gedcom_gedcom_proto protoreflect.FileDescriptor

var file_gedcom_gedcom_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x22, 0xbd, 0x06,
	0x0a, 0x06, 0x47, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x12, 0x31, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x65, 0x64, 0x63, 0x6f,
	0x6d, 0x2e, 0x47, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0b, 0x49,
	0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x64, 0x63, 0x6f, 0x6d,
	0x2e, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x52, 0x0b, 0x49, 0x6e, 0x64,
	0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x46, 0x61, 0x6d, 0x69,
	0x6c, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x65, 0x64,
	0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x52, 0x08, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x1a, 0x24, 0x0a, 0x0a, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x1a, 0xfb, 0x03, 0x0a, 0x0a, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x34, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e,
	0x49, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x41,
	0x0a, 0x0b, 0x42, 0x69, 0x72, 0x74, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x64,
	0x63, 0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x42, 0x69, 0x72, 0x74, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x41, 0x0a, 0x0b, 0x44, 0x65, 0x61, 0x74, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e,
	0x47, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61,
	0x6c, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x44, 0x65, 0x61, 0x74, 0x68, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x1a, 0x6b, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x65,
	0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x64, 0x69,
	0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x1a, 0x58, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x69, 0x76,
	0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x69,
	0x76, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x75, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x1a, 0x42, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x59, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x59, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x10, 0x0a,
	0x03, 0x44, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x61, 0x79, 0x1a,
	0x6c, 0x0a, 0x06, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x73, 0x42, 0x30, 0x5a,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x63, 0x68,
	0x65, 0x6e, 0x62, 0x6f, 0x65, 0x73, 0x6d, 0x61, 0x6e, 0x73, 0x2f, 0x67, 0x65, 0x64, 0x63, 0x6f,
	0x6d, 0x2d, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gedcom_gedcom_proto_rawDescOnce sync.Once
	file_gedcom_gedcom_proto_rawDescData = file_gedcom_gedcom_proto_rawDesc
)

func file_gedcom_gedcom_proto_rawDescGZIP() []byte {
	file_gedcom_gedcom_proto_rawDescOnce.Do(func() {
		file_gedcom_gedcom_proto_rawDescData = protoimpl.X.CompressGZIP(file_gedcom_gedcom_proto_rawDescData)
	})
	return file_gedcom_gedcom_proto_rawDescData
}

var file_gedcom_gedcom_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gedcom_gedcom_proto_goTypes = []interface{}{
	(*Gedcom)(nil),                  // 0: gedcom.Gedcom
	(*Gedcom_HeaderType)(nil),       // 1: gedcom.Gedcom.HeaderType
	(*Gedcom_Individual)(nil),       // 2: gedcom.Gedcom.Individual
	(*Gedcom_Family)(nil),           // 3: gedcom.Gedcom.Family
	(*Gedcom_Individual_Event)(nil), // 4: gedcom.Gedcom.Individual.Event
	(*Gedcom_Individual_Name)(nil),  // 5: gedcom.Gedcom.Individual.Name
	(*Gedcom_Individual_Date)(nil),  // 6: gedcom.Gedcom.Individual.Date
}
var file_gedcom_gedcom_proto_depIdxs = []int32{
	1, // 0: gedcom.Gedcom.Header:type_name -> gedcom.Gedcom.HeaderType
	2, // 1: gedcom.Gedcom.Individuals:type_name -> gedcom.Gedcom.Individual
	3, // 2: gedcom.Gedcom.Families:type_name -> gedcom.Gedcom.Family
	5, // 3: gedcom.Gedcom.Individual.Names:type_name -> gedcom.Gedcom.Individual.Name
	4, // 4: gedcom.Gedcom.Individual.BirthEvents:type_name -> gedcom.Gedcom.Individual.Event
	4, // 5: gedcom.Gedcom.Individual.DeathEvents:type_name -> gedcom.Gedcom.Individual.Event
	6, // 6: gedcom.Gedcom.Individual.Event.Date:type_name -> gedcom.Gedcom.Individual.Date
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_gedcom_gedcom_proto_init() }
func file_gedcom_gedcom_proto_init() {
	if File_gedcom_gedcom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gedcom_gedcom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gedcom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gedcom_gedcom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gedcom_HeaderType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gedcom_gedcom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gedcom_Individual); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gedcom_gedcom_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gedcom_Family); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gedcom_gedcom_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gedcom_Individual_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gedcom_gedcom_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gedcom_Individual_Name); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gedcom_gedcom_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gedcom_Individual_Date); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gedcom_gedcom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gedcom_gedcom_proto_goTypes,
		DependencyIndexes: file_gedcom_gedcom_proto_depIdxs,
		MessageInfos:      file_gedcom_gedcom_proto_msgTypes,
	}.Build()
	File_gedcom_gedcom_proto = out.File
	file_gedcom_gedcom_proto_rawDesc = nil
	file_gedcom_gedcom_proto_goTypes = nil
	file_gedcom_gedcom_proto_depIdxs = nil
}
