name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Install 7zip
      run: sudo apt-get install p7zip-full
      
    - name: Cross-compile
      run: bash ./crosscompile.sh
  
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
    # Artifact name
        name: binaries
    # A file, directory or wildcard pattern that describes what to upload
        path: gedcom-parser.*.7z
        retention-days: 90

